### ISSUE TITLE
transitiontime method does not work

### ISSUE THREAD

**Issue by spaceneedle** [aleroddepaz/pyhue#1]
Hello,

I am unable to get transitiontime working and receive an error. Here is an example of my code:

> bridge = pyhue.Bridge('my_ip_address', 'my_username')
> for light in bridge.lights:
>    light.on = True
>    light.hue = 0
>    light.transitiontime = 60

I performed a packet trace and noticed that on each method call, pyhue is performing a separate HTTP PUT. This would send "transitiontime" by itself, which probably makes no sense to the Hue bridge. 

Is there any way to batch calls or throw in transitiontime gracefully?

**Comment by aleroddepaz** [comment]
Hi @spaceneedle,

As you mention, properties only allow to set one attribute in a single HTTP request. If you want to update multiple values at one, use the `update` method:

```
for light in bridge.lights:
    light.on = True
    light.update(hue=0, transitiontime=60)
```

Please let me know if this solves your problem.

**Comment by spaceneedle** [comment]
This did the trick! Thanks!
