### ISSUE TITLE
AttributeError: 'list' object has no attribute 'keys'

### ISSUE THREAD

**Issue by PanderMusubi** [aleroddepaz/pyhue#2]
Please fix the following error or post a workaround.

$ python
Python 2.7.8 (default, Oct 20 2014, 15:05:19) 
[GCC 4.9.1] on linux2
Type "help", "copyright", "credits" or "license" for more information.

> > > import pyhue
> > > bridge = pyhue.Bridge('192.168.1.9', 'Philips hue')
> > > for light in bridge.lights:
> > > ...   light.on = True
> > > ...   light.hue = 0
> > > ... 
> > > Traceback (most recent call last):
> > >   File "<stdin>", line 1, in <module>
> > >   File "pyhue.py", line 55, in lights
> > >     return self.__get_api_objects(Light)
> > >   File "pyhue.py", line 50, in __get_api_objects
> > >     objects = [cls(self, i) for i in result.keys()]
> > > AttributeError: 'list' object has no attribute 'keys'

$ python3
Python 3.4.2 (default, Oct  8 2014, 13:08:17) 
[GCC 4.9.1] on linux
Type "help", "copyright", "credits" or "license" for more information.

> > > import pyhue
> > > bridge = pyhue.Bridge('192.168.1.9', 'Philips hue')
> > > for light in bridge.lights:
> > > ...   light.on = True
> > > ...   light.hue = 0
> > > ... 
> > > Traceback (most recent call last):
> > >   File "<stdin>", line 1, in <module>
> > >   File "/home/sander/Downloads/ph/a/pyhue-master/src/pyhue.py", line 55, in lights
> > >     return self.__get_api_objects(Light)
> > >   File "/home/sander/Downloads/ph/a/pyhue-master/src/pyhue.py", line 50, in __get_api_objects
> > >     objects = [cls(self, i) for i in result.keys()]
> > > AttributeError: 'list' object has no attribute 'keys'

**Comment by aleroddepaz** [comment]
Hi,

It looks like the bridge is returning a JSON list, but according to the official API, that request should return an object - maybe the space in the username causes an error?

Please post the response of a GET request to `http://192.168.1.9/Philips hue/lights` to confirm this.

**Comment by PanderMusubi** [comment]
(meanwhile the IP address ends with 10)

via postmen GET:
    <html>
        <head></head>
        <b>Page not found</b>
    </html>

via command line:
    $ wget http://192.168.1.10/Philips\ hue/lights 
    --2016-03-16 11:14:29--  http://192.168.1.10/Philips%20hue/lights
    Connecting to 192.168.1.10:80... connected.
    HTTP request sent, awaiting response... 404 Not Found
    2016-03-16 11:14:29 ERROR 404: Not Found.

via existing username:
  http://pastebin.com/QL8BnL1d

via wget:
    {"1":{"state": {"on":false,"bri":1,"hue":21844,"sat":254,"effect":"none","xy":[0.0000,0.0000],"ct":467,"alert":"none","colormode":"hs","reachable":false}, "type": "Extended color light", "name": "... "swversion": "66013105"}}

**Comment by PanderMusubi** [comment]
How can we move this issue forward? Thanks.
